# Generated by Django 4.1.1 on 2022-11-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('APOINID', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Appointment ID')),
                ('UID', models.CharField(max_length=150, verbose_name='User ID')),
                ('OFID', models.CharField(blank=True, max_length=150, null=True, verbose_name='Office ID')),
                ('BATCH', models.CharField(max_length=150, null=True, verbose_name='Batch')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual End Time')),
                ('date', models.DateField()),
                ('PST', models.TimeField(verbose_name='probable start time')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='batch',
            fields=[
                ('BATCHID', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Batch ID')),
                ('OFID', models.CharField(max_length=150, verbose_name='Office ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('start', models.TimeField(null=True, verbose_name='Start Time')),
                ('end', models.TimeField(null=True, verbose_name='End Time')),
                ('min', models.IntegerField(null=True, verbose_name='Minutes')),
                ('SLOTS', models.IntegerField(null=True, verbose_name='Slots per hour')),
                ('total_hours', models.IntegerField(null=True, verbose_name='Total Hours')),
                ('status', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
