# Generated by Django 4.1.1 on 2022-11-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='freeway',
            fields=[
                ('pno', models.CharField(max_length=150)),
                ('time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=150)),
                ('long', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('pin', models.CharField(max_length=150)),
                ('ip', models.CharField(default='', max_length=150)),
                ('token', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='guest_sos',
            fields=[
                ('pno', models.CharField(max_length=150)),
                ('time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=150)),
                ('long', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('pin', models.CharField(max_length=150)),
                ('ip', models.CharField(default='', max_length=150)),
                ('token', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='update_quads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('long', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
